### ISSUE TITLE
DDEV-Live images must be swappable so they can be tested

### ISSUE THREAD

**Issue by rfay** [drud/ddev-images#4]
## Bug Description:

As we discussed in our meeting last Wednesday, there is currently no way to change the images that DDEV-Live uses for nginx or php. That means there's no way to test these images in context.

So it's absolutely critical that DDEV-Live provide a way to use custom images (these images) for testing in the DDEV-Live context.

This issue was delegated to @dclear and @unn at the meeting. It should probably be moved to the ddev-live issue queue when you're ready to do so.

## Definition of Ready Checklist:

- [ ] Provides steps to reproduce
- [ ] Dependencies identified
- [ ] Sized by team

R<sup>Product Owner</sup> A<sup>Scrum Master</sup> C<sup>Eng. Lead</sup> I<sup>Team</sup>

## Definition of Done Checklist:

- [ ] Deployed on test environment
- [ ] Steps do not reproduce
- [ ] Unit test and E2E coverage updated (if applicable)
- [ ] Builds without errors
- [ ] Internal documentation updated (if required)

R<sup>Eng. Lead, Team</sup> A<sup>Scrum Master</sup> CI<sup>Product Owner</sup>

**Comment by dclear** [comment]
Issue moved to [drud/ddev-live #331](https://github.com/drud/ddev-live/issues/331) via [**ZenHub**](https://www.zenhub.com/)
